name: Trigger MSI Repo Workflow

on:
  push:
    branches: [ master ]

jobs:
  trigger-msi:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in MSI repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.REPO_MSI_TOKEN }}" \
            https://api.github.com/repos/ckjavahelpmate/MSI/actions/workflows/MSITest.yml/dispatches \
            -d '{"ref":"master"}'
